name = "{YOUR_WORKER_NAME}"
main = "worker.js"

compatibility_date = "2024-08-21"
compatibility_flags = [ "nodejs_compat" ]

no_bundle = true
workers_dev = true

send_metrics = true

[observability]
enabled = true
head_sampling_rate = 1

[vars]
# Control loading of different categories of stored configuration
USE_STORED_ADDRESS_CONFIGURATION = "true"
USE_STORED_USER_CONFIGURATION = "true"
# Control logging
CONSOLE_LOG_ENABLED = "false"
# Address configuration
DESTINATION = ""
REJECT_TREATMENT = ": Invalid recipient"
SUBADDRESSES = "*"
USERS = ""
# Error message configuration
UNVERIFIED_DESTINATION_ERROR_MESSAGE = "destination address not verified"
# Format configuration
FORMAT_ADDRESS_SEPARATOR = ","
FORMAT_FAILOVER_SEPARATOR = ":"
FORMAT_LOCAL_PART_SEPARATOR = "+"
FORMAT_REJECT_SEPARATOR = ";"
FORMAT_VALID_CUSTOM_HEADER_REGEXP = "X-.*"
FORMAT_VALID_EMAIL_ADDRESS_REGEXP = "^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$"
# Header configuration
CUSTOM_HEADER = "X-My-Email-Forwarding"
CUSTOM_HEADER_FAIL = "fail"
CUSTOM_HEADER_PASS = "pass"

[[kv_namespaces]]
binding = "MAP"
id = "{YOUR_KV_NAMESPACE_ID}"