name = "email-subaddressing"
compatibility_date = "2024-08-01"
main = "worker.js"

no_bundle = true
workers_dev = false

#[[kv_namespaces]]
#binding = "MAP"
#id = ""

#[vars]
#USERS = ""
#SUBADDRESSES = "*"
#SEPARATOR = "+"
#DESTINATION = ""
#FAILURE = "Invalid recipient"
#HEADER = "X-My-Email-Subaddressing"
