name = "${WRANGLER_NAME}"
main = "worker.js"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

kv_namespaces = [{ binding = "MAP", id = "${WRANGLER_KV_MAP_ID}" }]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
