name = "{YOUR_WORKER_NAME}"
main = "worker.js"

compatibility_date = "2024-08-21"
compatibility_flags = [ "nodejs_compat" ]

no_bundle = true
workers_dev = true

[vars]
# Loading control configuraiton
USE_STORED_USER_CONFIGURATION = "true"
USE_STORED_ADDRESS_GLOBAL_CONFIGURATION = "true"
USE_STORED_FORMAT_GLOBAL_CONFIGURATION = "false"
USE_STORED_FORWARD_RETRY_GLOBAL_CONFIGURATION = "false"
USE_STORED_HEADER_GLOBAL_CONFIGURATION = "false"
# Address configuration
DESTINATION = ""
REJECT_TREATMENT = ": Invalid recipient"
SUBADDRESSES = "*"
USERS = ""
# Format configuration
FORMAT_ADDRESS_SEPARATOR = ","
FORMAT_FAILURE_SEPARATOR = ";"
FORMAT_LOCAL_PART_SEPARATOR = "+"
# Header configuration
CUSTOM_HEADER = "X-My-Email-Subaddressing"
CUSTOM_HEADER_FAIL = "fail"
CUSTOM_HEADER_PASS = "pass"
# Forward retrying configuration
FORWARD_DESTINATION_NOT_VERIFIED_ERROR_MESSAGE = "destination address not verified"
FORWARD_RETRYING_MAX_RETRIES = "1"
FORWARD_RETRYING_TIMEOUT_MILLISECONDS = "1000"

[[kv_namespaces]]
binding = "MAP"
id = "{YOUR_KV_NAMESPACE_ID}"